services:

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: cantina
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cantina-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres-data:
